name: "1-1번"

on:
  on:
  workflow_dispatch:  # 수동 실행을 가능하게 하는 트리거
  push:
    branches:
      - main

jobs:
  tttt:
    runs-on: ubuntu-latest
    steps:
      - name: 1-1번 워크플로우 실행
        run: echo "1-1번 워크플로우가 실행되었습니다."
