name: "a"

on:
  workflow_dispatch:  # 수동 실행을 가능하게 하는 트리거
  push:
    branches:
      - main

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - name: a 워크플로우 실행
        run: echo "a 워크플로우가 실행되었습니다."
