name: "e"

on:
  workflow_dispatch:  # 수동 실행을 가능하게 하는 트리거
  workflow_run:
    workflows: ["a", "b", "c", "d"]  # 다른 워크플로우가 완료된 후 실행
    types:
      - completed

jobs:
  e:
    runs-on: ubuntu-latest
    steps:
      - name: e 워크플로우 실행
        run: echo "e 워크플로우가 실행되었습니다."
