name: "IndexNow 삭제"

on:
  repository_dispatch:
    types:
      - indexnow-delete

concurrency:
  group: indexnow-workflow-group
  cancel-in-progress: false

jobs:
  b:
    runs-on: ubuntu-latest
    steps:
      - name: b 워크플로우 실행
        run: echo "b 워크플로우가 실행되었습니다."
