name: "IndexNow 수정"

on:
  repository_dispatch:
    types:
      - indexnow-modify

concurrency:
  group: indexnow-workflow-group
  cancel-in-progress: false

jobs:
  c:
    runs-on: ubuntu-latest
    steps:
      - name: c 워크플로우 실행
        run: echo "c 워크플로우가 실행되었습니다."
