name: "IndexNow 수정"

on:
  workflow_dispatch:  # 수동 실행을 가능하게 하는 트리거
  push:
    branches:
      - main

jobs:
  c:
    runs-on: ubuntu-latest
    steps:
      - name: c 워크플로우 실행
        run: echo "c 워크플로우가 실행되었습니다."
