name: "IndexNow 추가"

on:
  repository_dispatch:
    types:
      - indexnow-add

concurrency:
  group: indexnow-workflow-group
  cancel-in-progress: false

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
      - name: a 워크플로우 실행
        run: echo "a 워크플로우가 실행되었습니다."
