name: "공개 저장소로 빌드 및 배포"
on:
  push:
    branches:
      - main
      - master
  repository_dispatch:
    types:
      - pages-deploy
  workflow_dispatch:  # 수동 실행을 추가
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: A 워크플로우 실행
        run: echo "A 워크플로우가 실행되었습니다."
