name: "페이지"

on:
  workflow_run:
    workflows: ["IndexNow 추가"]
    types:
      - completed

  workflow_run:
    workflows: ["IndexNow 수정"]
    types:
      - completed

  workflow_run:
    workflows: ["IndexNow 삭제"]
    types:
      - completed


concurrency:
  group: indexnow-workflow-group
  cancel-in-progress: false

jobs:
  e:
    runs-on: ubuntu-latest
    steps:
      - name: e 워크플로우 실행
        run: echo "e 워크플로우가 실행되었습니다."
